stages: [build, deploy]

build:
  stage: build
  image: node:20
  script:
    - npm ci
    - npm run build -- --configuration=production
  artifacts:
    paths: [dist/]
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

aws_smoke:
  stage: deploy
  image: public.ecr.aws/aws-cli/aws-cli:2.17.40
  script:
    - set -euo pipefail
    # Show exact characters you typed: 2d 2d must appear for the two hyphens
    - printf 'aws --version\n' | od -An -t x1
    - aws --version
    - aws sts get-caller-identity
    - aws s3 ls "s3://${S3_BUCKET}" || true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

