stages: [build, deploy]

build:
  stage: build
  image: node:20
  script:
    - npm ci
    - npm run build -- --configuration=production
  artifacts:
    paths: [dist/]
    expire_in: 1 week
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'

deploy:
  stage: deploy
  image: public.ecr.aws/aws-cli/aws-cli:2.17.40
  needs: ["build"]
  variables:
    AWS_DEFAULT_REGION: "eu-west-3"
  script:
    - set -euo pipefail
    - aws --version
    - aws sts get-caller-identity
    # Angular 16+: build can be dist/<app>/ or dist/<app>/browser/
    - DIST_DIR="$(ls -d dist/*/browser/ dist/*/ 2>/dev/null | head -n 1)"
    - echo "DIST_DIR=${DIST_DIR}"
    # 1) All hashed assets => long cache
    - aws s3 cp "${DIST_DIR}" "s3://${S3_BUCKET}/" --recursive \
        --exclude "index.html" --exclude "assets/config.json" \
        --cache-control "public,max-age=31536000,immutable"
    # 2) index.html => no cache
    - aws s3 cp "${DIST_DIR}index.html" "s3://${S3_BUCKET}/index.html" \
        --cache-control "no-cache,no-store,must-revalidate" \
        --content-type "text/html"
    # 3) assets/config.json => no cache (if present)
    - |
      if [ -f "${DIST_DIR}assets/config.json" ]; then
        aws s3 cp "${DIST_DIR}assets/config.json" "s3://${S3_BUCKET}/assets/config.json" \
          --cache-control "no-cache" --content-type "application/json";
      else
        echo "WARNING: ${DIST_DIR}assets/config.json not found";
      fi
    # 4) Targeted invalidation
    - aws cloudfront create-invalidation --distribution-id "${CF_DIST_ID}" --paths "/index.html" "/assets/config.json"
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
  environment:
    name: production

